# ═══════════════════════════════════════════════════
# narrow width [128, 256, 512, 512, 512, 512]
# ═══════════════════════════════════════════════════

f32c32_shallow_narrow:
  latent_channels: 32
  enc_width: [128, 256, 512, 512, 512, 512]
  enc_depth: [1, 1, 1, 1, 1, 1]
  dec_depth: [1, 1, 1, 1, 1, 1]

f32c32_regular_narrow:
  latent_channels: 32
  enc_width: [128, 256, 512, 512, 512, 512]
  enc_depth: [2, 2, 2, 3, 3, 3]
  dec_depth: [3, 3, 3, 3, 3, 3]

f32c128_shallow_narrow:
  latent_channels: 128
  enc_width: [128, 256, 512, 512, 512, 512]
  enc_depth: [1, 1, 1, 1, 1, 1]
  dec_depth: [1, 1, 1, 1, 1, 1]

f32c128_regular_narrow:
  latent_channels: 128
  enc_width: [128, 256, 512, 512, 512, 512]
  enc_depth: [2, 2, 2, 3, 3, 3]
  dec_depth: [3, 3, 3, 3, 3, 3]

f32c256_shallow_narrow:
  latent_channels: 256
  enc_width: [128, 256, 512, 512, 512, 512]
  enc_depth: [1, 1, 1, 1, 1, 1]
  dec_depth: [1, 1, 1, 1, 1, 1]

f32c256_regular_narrow:
  latent_channels: 256
  enc_width: [128, 256, 512, 512, 512, 512]
  enc_depth: [2, 2, 2, 3, 3, 3]
  dec_depth: [3, 3, 3, 3, 3, 3]

# ═══════════════════════════════════════════════════
# wide width [128, 256, 512, 512, 1024, 1024]
# ═══════════════════════════════════════════════════

f32c32_shallow_wide:
  latent_channels: 32
  enc_width: [128, 256, 512, 512, 1024, 1024]
  enc_depth: [1, 1, 1, 1, 1, 1]
  dec_depth: [1, 1, 1, 1, 1, 1]

f32c32_regular_wide:
  latent_channels: 32
  enc_width: [128, 256, 512, 512, 1024, 1024]
  enc_depth: [2, 2, 2, 3, 3, 3]
  dec_depth: [3, 3, 3, 3, 3, 3]

f32c128_shallow_wide:
  latent_channels: 128
  enc_width: [128, 256, 512, 512, 1024, 1024]
  enc_depth: [1, 1, 1, 1, 1, 1]
  dec_depth: [1, 1, 1, 1, 1, 1]

f32c128_regular_wide:
  latent_channels: 128
  enc_width: [128, 256, 512, 512, 1024, 1024]
  enc_depth: [2, 2, 2, 3, 3, 3]
  dec_depth: [3, 3, 3, 3, 3, 3]

f32c256_shallow_wide:
  latent_channels: 256
  enc_width: [128, 256, 512, 512, 1024, 1024]
  enc_depth: [1, 1, 1, 1, 1, 1]
  dec_depth: [1, 1, 1, 1, 1, 1]

f32c256_regular_wide:
  latent_channels: 256
  enc_width: [128, 256, 512, 512, 1024, 1024]
  enc_depth: [2, 2, 2, 3, 3, 3]
  dec_depth: [3, 3, 3, 3, 3, 3]
